// <auto-generated />
using System;
using System.Collections.Generic;
using HelpDev.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace HelpDev.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260720135553_AddSecurityAuditV1")]
    partial class AddSecurityAuditV1
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("HelpDev.Infrastructure.Outbox.OutboxMessage", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<int>("AttemptCount")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0)
                        .HasColumnName("attempt_count");

                    b.Property<string>("Error")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)")
                        .HasColumnName("error");

                    b.Property<DateTime?>("LastAttemptAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_attempt_at_utc");

                    b.Property<string>("LockId")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("lock_id");

                    b.Property<DateTime?>("LockedUntilUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("locked_until_utc");

                    b.Property<DateTime>("OccurredAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("occurred_at_utc");

                    b.Property<string>("Payload")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("payload");

                    b.Property<DateTime?>("ProcessedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("processed_at_utc");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("type");

                    b.HasKey("Id");

                    b.HasIndex("LockedUntilUtc")
                        .HasDatabaseName("ix_outbox_messages_locked_until");

                    b.HasIndex("ProcessedAtUtc", "OccurredAtUtc")
                        .HasDatabaseName("ix_outbox_messages_processed_occurred");

                    b.HasIndex("ProcessedAtUtc", "AttemptCount", "OccurredAtUtc")
                        .HasDatabaseName("ix_outbox_messages_pending");

                    b.ToTable("outbox_messages", (string)null);
                });

            modelBuilder.Entity("HelpDev.Modules.Administration.Domain.Announcements.Announcement", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<string>("Body")
                        .IsRequired()
                        .HasMaxLength(5000)
                        .HasColumnType("character varying(5000)")
                        .HasColumnName("body");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at_utc");

                    b.Property<DateTime?>("EndsAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("ends_at_utc");

                    b.Property<DateTime?>("PublishedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("published_at_utc");

                    b.Property<DateTime?>("StartsAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("starts_at_utc");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("status");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("title");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("type");

                    b.Property<DateTime>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at_utc");

                    b.HasKey("Id");

                    b.HasIndex("EndsAtUtc")
                        .HasDatabaseName("ix_administration_announcements_ends_at_utc");

                    b.HasIndex("StartsAtUtc")
                        .HasDatabaseName("ix_administration_announcements_starts_at_utc");

                    b.HasIndex("Status")
                        .HasDatabaseName("ix_administration_announcements_status");

                    b.HasIndex("Type")
                        .HasDatabaseName("ix_administration_announcements_type");

                    b.HasIndex("UpdatedAtUtc")
                        .HasDatabaseName("ix_administration_announcements_updated_at_utc");

                    b.ToTable("administration_announcements", (string)null);
                });

            modelBuilder.Entity("HelpDev.Modules.Administration.Domain.FeatureFlags.FeatureFlag", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at_utc");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("description");

                    b.Property<bool>("IsEnabled")
                        .HasColumnType("boolean")
                        .HasColumnName("is_enabled");

                    b.Property<string>("Key")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("key");

                    b.Property<DateTime>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at_utc");

                    b.HasKey("Id");

                    b.HasIndex("IsEnabled")
                        .HasDatabaseName("ix_administration_feature_flags_is_enabled");

                    b.HasIndex("Key")
                        .IsUnique()
                        .HasDatabaseName("ux_administration_feature_flags_key");

                    b.ToTable("administration_feature_flags", (string)null);
                });

            modelBuilder.Entity("HelpDev.Modules.Administration.Domain.Settings.SystemSetting", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at_utc");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("description");

                    b.Property<bool>("IsPublic")
                        .HasColumnType("boolean")
                        .HasColumnName("is_public");

                    b.Property<string>("Key")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("key");

                    b.Property<DateTime>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at_utc");

                    b.Property<string>("Value")
                        .IsRequired()
                        .HasMaxLength(4000)
                        .HasColumnType("character varying(4000)")
                        .HasColumnName("value");

                    b.Property<string>("ValueType")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("value_type");

                    b.HasKey("Id");

                    b.HasIndex("IsPublic")
                        .HasDatabaseName("ix_administration_system_settings_is_public");

                    b.HasIndex("Key")
                        .IsUnique()
                        .HasDatabaseName("ux_administration_system_settings_key");

                    b.ToTable("administration_system_settings", (string)null);
                });

            modelBuilder.Entity("HelpDev.Modules.Analytics.Domain.Events.AnalyticsEventReceipt", b =>
                {
                    b.Property<Guid>("EventId")
                        .HasColumnType("uuid");

                    b.Property<string>("ErrorCode")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("error_code");

                    b.Property<string>("EventType")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("character varying(80)")
                        .HasColumnName("event_type");

                    b.Property<DateOnly>("MetricDateUtc")
                        .HasColumnType("date")
                        .HasColumnName("metric_date_utc");

                    b.Property<DateTime>("OccurredAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("occurred_at_utc");

                    b.Property<DateTime>("ProcessedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("processed_at_utc");

                    b.Property<string>("ProcessingStatus")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("processing_status");

                    b.Property<int>("SchemaVersion")
                        .HasColumnType("integer")
                        .HasColumnName("schema_version");

                    b.HasKey("EventId");

                    b.HasIndex("EventType")
                        .HasDatabaseName("ix_analytics_event_receipts_event_type");

                    b.HasIndex("MetricDateUtc")
                        .HasDatabaseName("ix_analytics_event_receipts_metric_date_utc");

                    b.HasIndex("ProcessedAtUtc")
                        .HasDatabaseName("ix_analytics_event_receipts_processed_at_utc");

                    b.ToTable("analytics_event_receipts", (string)null);
                });

            modelBuilder.Entity("HelpDev.Modules.Analytics.Domain.Metrics.AnalyticsSubjectSnapshot", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("display_name");

                    b.Property<string>("Slug")
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)")
                        .HasColumnName("slug");

                    b.Property<Guid>("SubjectId")
                        .HasColumnType("uuid")
                        .HasColumnName("subject_id");

                    b.Property<string>("SubjectType")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("character varying(40)")
                        .HasColumnName("subject_type");

                    b.Property<DateTime>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at_utc");

                    b.HasKey("Id");

                    b.HasIndex("SubjectType")
                        .HasDatabaseName("ix_analytics_subject_snapshots_subject_type");

                    b.HasIndex("SubjectType", "SubjectId")
                        .IsUnique()
                        .HasDatabaseName("ux_analytics_subject_snapshots_subject_type_subject_id");

                    b.ToTable("analytics_subject_snapshots", (string)null);
                });

            modelBuilder.Entity("HelpDev.Modules.Analytics.Domain.Metrics.DailyActiveUser", b =>
                {
                    b.Property<DateOnly>("DateUtc")
                        .HasColumnType("date")
                        .HasColumnName("date_utc");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.Property<DateTime>("FirstSeenAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("first_seen_at_utc");

                    b.HasKey("DateUtc", "UserId");

                    b.HasIndex("DateUtc")
                        .HasDatabaseName("ix_analytics_daily_active_users_date_utc");

                    b.HasIndex("UserId")
                        .HasDatabaseName("ix_analytics_daily_active_users_user_id");

                    b.ToTable("analytics_daily_active_users", (string)null);
                });

            modelBuilder.Entity("HelpDev.Modules.Analytics.Domain.Metrics.DailyMetric", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<long>("Count")
                        .HasColumnType("bigint")
                        .HasColumnName("count");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at_utc");

                    b.Property<DateOnly>("DateUtc")
                        .HasColumnType("date")
                        .HasColumnName("date_utc");

                    b.Property<string>("Dimension1Key")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("dimension1_key");

                    b.Property<string>("Dimension1Value")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("dimension1_value");

                    b.Property<string>("Dimension2Key")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("dimension2_key");

                    b.Property<string>("Dimension2Value")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("dimension2_value");

                    b.Property<long>("FailureCount")
                        .HasColumnType("bigint")
                        .HasColumnName("failure_count");

                    b.Property<long>("MaxDurationMilliseconds")
                        .HasColumnType("bigint")
                        .HasColumnName("max_duration_milliseconds");

                    b.Property<string>("MetricKey")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("character varying(80)")
                        .HasColumnName("metric_key");

                    b.Property<long>("MinDurationMilliseconds")
                        .HasColumnType("bigint")
                        .HasColumnName("min_duration_milliseconds");

                    b.Property<Guid?>("SubjectId")
                        .HasColumnType("uuid")
                        .HasColumnName("subject_id");

                    b.Property<string>("SubjectType")
                        .HasMaxLength(40)
                        .HasColumnType("character varying(40)")
                        .HasColumnName("subject_type");

                    b.Property<long>("SuccessCount")
                        .HasColumnType("bigint")
                        .HasColumnName("success_count");

                    b.Property<long>("TotalDurationMilliseconds")
                        .HasColumnType("bigint")
                        .HasColumnName("total_duration_milliseconds");

                    b.Property<DateTime>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at_utc");

                    b.HasKey("Id");

                    b.HasIndex("DateUtc")
                        .HasDatabaseName("ix_analytics_daily_metrics_date_utc");

                    b.HasIndex("MetricKey", "DateUtc")
                        .HasDatabaseName("ix_analytics_daily_metrics_metric_key_date_utc");

                    b.HasIndex("DateUtc", "MetricKey", "SubjectId", "SubjectType", "Dimension1Key", "Dimension1Value", "Dimension2Key", "Dimension2Value")
                        .IsUnique()
                        .HasDatabaseName("ux_analytics_daily_metrics_identity");

                    NpgsqlIndexBuilderExtensions.AreNullsDistinct(b.HasIndex("DateUtc", "MetricKey", "SubjectId", "SubjectType", "Dimension1Key", "Dimension1Value", "Dimension2Key", "Dimension2Value"), false);

                    b.ToTable("analytics_daily_metrics", (string)null);
                });

            modelBuilder.Entity("HelpDev.Modules.Auditing.Domain.Records.AuditRecord", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Action")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)")
                        .HasColumnName("action");

                    b.Property<string>("ActorType")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasColumnName("actor_type");

                    b.Property<Guid?>("ActorUserId")
                        .HasColumnType("uuid")
                        .HasColumnName("actor_user_id");

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("category");

                    b.Property<string>("CorrelationId")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("correlation_id");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at_utc");

                    b.Property<IReadOnlyDictionary<string, string>>("Metadata")
                        .HasColumnType("jsonb")
                        .HasColumnName("metadata");

                    b.Property<DateTime>("OccurredAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("occurred_at_utc");

                    b.Property<string>("Outcome")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasColumnName("outcome");

                    b.Property<string>("ReasonCode")
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)")
                        .HasColumnName("reason_code");

                    b.Property<string>("RequestMethod")
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)")
                        .HasColumnName("request_method");

                    b.Property<string>("RequestPathTemplate")
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)")
                        .HasColumnName("request_path_template");

                    b.Property<string>("SubjectDisplay")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("subject_display");

                    b.Property<Guid?>("SubjectId")
                        .HasColumnType("uuid")
                        .HasColumnName("subject_id");

                    b.Property<string>("SubjectType")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("subject_type");

                    b.HasKey("Id");

                    b.HasIndex("CorrelationId")
                        .HasDatabaseName("ix_audit_records_correlation_id");

                    b.HasIndex("OccurredAtUtc")
                        .HasDatabaseName("ix_audit_records_occurred_at_utc");

                    b.HasIndex("Action", "OccurredAtUtc")
                        .HasDatabaseName("ix_audit_records_action_occurred_at_utc");

                    b.HasIndex("ActorUserId", "OccurredAtUtc")
                        .HasDatabaseName("ix_audit_records_actor_user_id_occurred_at_utc");

                    b.HasIndex("Category", "OccurredAtUtc")
                        .HasDatabaseName("ix_audit_records_category_occurred_at_utc");

                    b.HasIndex("Outcome", "OccurredAtUtc")
                        .HasDatabaseName("ix_audit_records_outcome_occurred_at_utc");

                    b.HasIndex("SubjectType", "SubjectId", "OccurredAtUtc")
                        .HasDatabaseName("ix_audit_records_subject_occurred_at_utc");

                    b.ToTable("audit_records", (string)null);
                });

            modelBuilder.Entity("HelpDev.Modules.Content.Domain.Entities.Content", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<Guid>("AuthorId")
                        .HasColumnType("uuid")
                        .HasColumnName("author_id");

                    b.Property<string>("Body")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("body");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<int>("Saves")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0)
                        .HasColumnName("saves");

                    b.Property<string>("Slug")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)")
                        .HasColumnName("slug");

                    b.Property<string>("Status")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasDefaultValue("Draft")
                        .HasColumnName("status");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)")
                        .HasColumnName("title");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("type");

                    b.Property<int>("Views")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0)
                        .HasColumnName("views");

                    b.HasKey("Id");

                    b.HasIndex("AuthorId");

                    b.HasIndex("Slug")
                        .IsUnique();

                    b.HasIndex("Status");

                    b.HasIndex("Type");

                    b.ToTable("contents", (string)null);
                });

            modelBuilder.Entity("HelpDev.Modules.Identity.Domain.Entities.User", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Email")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasDefaultValue("")
                        .HasColumnName("email");

                    b.Property<string>("Expertise")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasDefaultValue("")
                        .HasColumnName("expertise");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasDefaultValue("")
                        .HasColumnName("first_name");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("full_name");

                    b.Property<string>("Interests")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasDefaultValue("")
                        .HasColumnName("interests");

                    b.Property<DateTime?>("LastLogin")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_login");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasDefaultValue("")
                        .HasColumnName("last_name");

                    b.Property<string>("Mobile")
                        .IsRequired()
                        .HasMaxLength(15)
                        .HasColumnType("character varying(15)")
                        .HasColumnName("mobile");

                    b.Property<string>("ProfileImageUrl")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasDefaultValue("")
                        .HasColumnName("profile_image_url");

                    b.Property<string>("Role")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasDefaultValue("User")
                        .HasColumnName("role");

                    b.Property<string>("Stack")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasDefaultValue("")
                        .HasColumnName("stack");

                    b.HasKey("Id");

                    b.HasIndex("Mobile")
                        .IsUnique();

                    b.ToTable("users", (string)null);
                });

            modelBuilder.Entity("HelpDev.Modules.Learning.Domain.Courses.Course", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("description");

                    b.Property<Guid>("InstructorId")
                        .HasColumnType("uuid")
                        .HasColumnName("instructor_id");

                    b.Property<DateTime?>("PublishedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("published_at");

                    b.Property<string>("Slug")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)")
                        .HasColumnName("slug");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("status");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)")
                        .HasColumnName("title");

                    b.HasKey("Id");

                    b.HasIndex("Slug")
                        .IsUnique();

                    b.ToTable("courses", (string)null);
                });

            modelBuilder.Entity("HelpDev.Modules.Learning.Domain.Courses.Lesson", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("ContentId")
                        .HasColumnType("uuid")
                        .HasColumnName("content_id");

                    b.Property<int?>("DurationMinutes")
                        .HasColumnType("integer")
                        .HasColumnName("duration_minutes");

                    b.Property<bool>("IsPreview")
                        .HasColumnType("boolean")
                        .HasColumnName("is_preview");

                    b.Property<int>("Order")
                        .HasColumnType("integer")
                        .HasColumnName("order");

                    b.Property<Guid>("SectionId")
                        .HasColumnType("uuid")
                        .HasColumnName("section_id");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)")
                        .HasColumnName("title");

                    b.Property<string>("VideoUrl")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)")
                        .HasColumnName("video_url");

                    b.HasKey("Id");

                    b.HasIndex("SectionId", "Order")
                        .IsUnique();

                    b.ToTable("course_lessons", (string)null);
                });

            modelBuilder.Entity("HelpDev.Modules.Learning.Domain.Courses.Section", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<Guid>("CourseId")
                        .HasColumnType("uuid")
                        .HasColumnName("course_id");

                    b.Property<int>("Order")
                        .HasColumnType("integer")
                        .HasColumnName("order");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)")
                        .HasColumnName("title");

                    b.HasKey("Id");

                    b.HasIndex("CourseId", "Order")
                        .IsUnique();

                    b.ToTable("course_sections", (string)null);
                });

            modelBuilder.Entity("HelpDev.Modules.Learning.Domain.Enrollments.Enrollment", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<Guid>("CourseId")
                        .HasColumnType("uuid")
                        .HasColumnName("course_id");

                    b.Property<DateTime>("EnrolledAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("enrolled_at");

                    b.Property<int>("ProgressPercentage")
                        .HasColumnType("integer")
                        .HasColumnName("progress_percentage");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("status");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.HasKey("Id");

                    b.HasIndex("CourseId", "UserId")
                        .IsUnique();

                    b.ToTable("enrollments", (string)null);
                });

            modelBuilder.Entity("HelpDev.Modules.Learning.Domain.Enrollments.LessonProgress", b =>
                {
                    b.Property<Guid>("EnrollmentId")
                        .HasColumnType("uuid")
                        .HasColumnName("enrollment_id");

                    b.Property<Guid>("LessonId")
                        .HasColumnType("uuid")
                        .HasColumnName("lesson_id");

                    b.Property<DateTime?>("CompletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("completed_at");

                    b.Property<DateTime?>("StartedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("started_at");

                    b.HasKey("EnrollmentId", "LessonId");

                    b.HasIndex("EnrollmentId", "LessonId")
                        .IsUnique();

                    b.ToTable("lesson_progresses", (string)null);
                });

            modelBuilder.Entity("HelpDev.Modules.PromptLab.Domain.Categories.PromptCategory", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at_utc");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("description");

                    b.Property<int>("DisplayOrder")
                        .HasColumnType("integer")
                        .HasColumnName("display_order");

                    b.Property<string>("Icon")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("icon");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean")
                        .HasColumnName("is_active");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("name");

                    b.Property<string>("Slug")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("slug");

                    b.Property<DateTime>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at_utc");

                    b.HasKey("Id");

                    b.HasIndex("DisplayOrder")
                        .HasDatabaseName("ix_promptlab_categories_display_order");

                    b.HasIndex("IsActive")
                        .HasDatabaseName("ix_promptlab_categories_is_active");

                    b.HasIndex("Slug")
                        .IsUnique()
                        .HasDatabaseName("ux_promptlab_categories_slug");

                    b.ToTable("promptlab_categories", (string)null);
                });

            modelBuilder.Entity("HelpDev.Modules.PromptLab.Domain.Favorites.PromptFavorite", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at_utc");

                    b.Property<Guid>("PromptDefinitionId")
                        .HasColumnType("uuid")
                        .HasColumnName("prompt_definition_id");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.HasKey("Id");

                    b.HasIndex("PromptDefinitionId")
                        .HasDatabaseName("ix_promptlab_favorites_prompt_definition_id");

                    b.HasIndex("UserId")
                        .HasDatabaseName("ix_promptlab_favorites_user_id");

                    b.HasIndex("UserId", "PromptDefinitionId")
                        .IsUnique()
                        .HasDatabaseName("ux_promptlab_favorites_user_id_prompt_definition_id");

                    b.ToTable("promptlab_favorites", (string)null);
                });

            modelBuilder.Entity("HelpDev.Modules.PromptLab.Domain.Prompts.PromptDefinition", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<bool>("AllowHistory")
                        .HasColumnType("boolean")
                        .HasColumnName("allow_history");

                    b.Property<Guid>("CategoryId")
                        .HasColumnType("uuid")
                        .HasColumnName("category_id");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at_utc");

                    b.Property<string>("Description")
                        .HasMaxLength(3000)
                        .HasColumnType("character varying(3000)")
                        .HasColumnName("description");

                    b.Property<int>("DisplayOrder")
                        .HasColumnType("integer")
                        .HasColumnName("display_order");

                    b.Property<bool>("IsEnabled")
                        .HasColumnType("boolean")
                        .HasColumnName("is_enabled");

                    b.Property<bool>("IsPublished")
                        .HasColumnType("boolean")
                        .HasColumnName("is_published");

                    b.Property<int>("LatestVersionNumber")
                        .HasColumnType("integer")
                        .HasColumnName("latest_version_number");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)")
                        .HasColumnName("name");

                    b.Property<DateTime?>("PublishedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("published_at_utc");

                    b.Property<int?>("PublishedVersionNumber")
                        .HasColumnType("integer")
                        .HasColumnName("published_version_number");

                    b.Property<string>("Purpose")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("character varying(40)")
                        .HasColumnName("purpose");

                    b.Property<bool>("RequiresAuthentication")
                        .HasColumnType("boolean")
                        .HasColumnName("requires_authentication");

                    b.Property<string>("Slug")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)")
                        .HasColumnName("slug");

                    b.Property<string>("Summary")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)")
                        .HasColumnName("summary");

                    b.Property<DateTime>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at_utc");

                    b.Property<string>("Visibility")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("character varying(40)")
                        .HasColumnName("visibility");

                    b.HasKey("Id");

                    b.HasIndex("CategoryId")
                        .HasDatabaseName("ix_promptlab_prompts_category_id");

                    b.HasIndex("DisplayOrder")
                        .HasDatabaseName("ix_promptlab_prompts_display_order");

                    b.HasIndex("IsEnabled")
                        .HasDatabaseName("ix_promptlab_prompts_is_enabled");

                    b.HasIndex("IsPublished")
                        .HasDatabaseName("ix_promptlab_prompts_is_published");

                    b.HasIndex("PublishedVersionNumber")
                        .HasDatabaseName("ix_promptlab_prompts_published_version_number");

                    b.HasIndex("Purpose")
                        .HasDatabaseName("ix_promptlab_prompts_purpose");

                    b.HasIndex("Slug")
                        .IsUnique()
                        .HasDatabaseName("ux_promptlab_prompts_slug");

                    b.HasIndex("Visibility")
                        .HasDatabaseName("ix_promptlab_prompts_visibility");

                    b.ToTable("promptlab_prompts", (string)null);
                });

            modelBuilder.Entity("HelpDev.Modules.PromptLab.Domain.Prompts.PromptVariable", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<string>("DefaultValue")
                        .HasMaxLength(20000)
                        .HasColumnType("character varying(20000)")
                        .HasColumnName("default_value");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("description");

                    b.Property<int>("DisplayOrder")
                        .HasColumnType("integer")
                        .HasColumnName("display_order");

                    b.Property<bool>("IsRequired")
                        .HasColumnType("boolean")
                        .HasColumnName("is_required");

                    b.Property<string>("Label")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)")
                        .HasColumnName("label");

                    b.Property<int?>("MaxLength")
                        .HasColumnType("integer")
                        .HasColumnName("max_length");

                    b.Property<decimal?>("MaxValue")
                        .HasPrecision(18, 6)
                        .HasColumnType("numeric(18,6)")
                        .HasColumnName("max_value");

                    b.Property<int?>("MinLength")
                        .HasColumnType("integer")
                        .HasColumnName("min_length");

                    b.Property<decimal?>("MinValue")
                        .HasPrecision(18, 6)
                        .HasColumnType("numeric(18,6)")
                        .HasColumnName("min_value");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("name");

                    b.Property<Guid>("PromptVersionId")
                        .HasColumnType("uuid")
                        .HasColumnName("prompt_version_id");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("character varying(40)")
                        .HasColumnName("type");

                    b.Property<string>("ValidationPattern")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("validation_pattern");

                    b.Property<string>("_allowedValues")
                        .IsRequired()
                        .HasMaxLength(8000)
                        .HasColumnType("character varying(8000)")
                        .HasColumnName("allowed_values_json");

                    b.HasKey("Id");

                    b.HasIndex("DisplayOrder")
                        .HasDatabaseName("ix_promptlab_variables_display_order");

                    b.HasIndex("PromptVersionId")
                        .HasDatabaseName("ix_promptlab_variables_prompt_version_id");

                    b.HasIndex("PromptVersionId", "Name")
                        .IsUnique()
                        .HasDatabaseName("ux_promptlab_variables_prompt_version_id_name");

                    b.ToTable("promptlab_variables", (string)null);
                });

            modelBuilder.Entity("HelpDev.Modules.PromptLab.Domain.Prompts.PromptVersion", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<string>("ChangeNotes")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)")
                        .HasColumnName("change_notes");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at_utc");

                    b.Property<Guid?>("CreatedByUserId")
                        .HasColumnType("uuid")
                        .HasColumnName("created_by_user_id");

                    b.Property<Guid>("PromptDefinitionId")
                        .HasColumnType("uuid")
                        .HasColumnName("prompt_definition_id");

                    b.Property<string>("Template")
                        .IsRequired()
                        .HasMaxLength(20000)
                        .HasColumnType("character varying(20000)")
                        .HasColumnName("template");

                    b.Property<int>("VersionNumber")
                        .HasColumnType("integer")
                        .HasColumnName("version_number");

                    b.HasKey("Id");

                    b.HasIndex("CreatedAtUtc")
                        .HasDatabaseName("ix_promptlab_versions_created_at_utc");

                    b.HasIndex("PromptDefinitionId")
                        .HasDatabaseName("ix_promptlab_versions_prompt_definition_id");

                    b.HasIndex("PromptDefinitionId", "VersionNumber")
                        .IsUnique()
                        .HasDatabaseName("ux_promptlab_versions_prompt_definition_id_version_number");

                    b.ToTable("promptlab_versions", (string)null);
                });

            modelBuilder.Entity("HelpDev.Modules.PromptLab.Domain.Rendering.PromptRenderRecord", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<int>("DurationMilliseconds")
                        .HasColumnType("integer")
                        .HasColumnName("duration_milliseconds");

                    b.Property<string>("ErrorCode")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("error_code");

                    b.Property<string>("InputPreview")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("input_preview");

                    b.Property<Guid>("PromptDefinitionId")
                        .HasColumnType("uuid")
                        .HasColumnName("prompt_definition_id");

                    b.Property<Guid>("PromptVersionId")
                        .HasColumnType("uuid")
                        .HasColumnName("prompt_version_id");

                    b.Property<DateTime>("RenderedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("rendered_at_utc");

                    b.Property<string>("RenderedPreview")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)")
                        .HasColumnName("rendered_preview");

                    b.Property<bool>("Succeeded")
                        .HasColumnType("boolean")
                        .HasColumnName("succeeded");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.Property<int>("VersionNumber")
                        .HasColumnType("integer")
                        .HasColumnName("version_number");

                    b.HasKey("Id");

                    b.HasIndex("PromptDefinitionId")
                        .HasDatabaseName("ix_promptlab_render_records_prompt_definition_id");

                    b.HasIndex("PromptVersionId")
                        .HasDatabaseName("ix_promptlab_render_records_prompt_version_id");

                    b.HasIndex("RenderedAtUtc")
                        .HasDatabaseName("ix_promptlab_render_records_rendered_at_utc");

                    b.HasIndex("Succeeded")
                        .HasDatabaseName("ix_promptlab_render_records_succeeded");

                    b.HasIndex("UserId")
                        .HasDatabaseName("ix_promptlab_render_records_user_id");

                    b.ToTable("promptlab_render_records", (string)null);
                });

            modelBuilder.Entity("HelpDev.Modules.Search.Domain.SearchDocument", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("IndexedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("indexed_at_utc");

                    b.Property<bool>("IsPublished")
                        .HasColumnType("boolean")
                        .HasColumnName("is_published");

                    b.Property<Guid>("LastEventId")
                        .HasColumnType("uuid")
                        .HasColumnName("last_event_id");

                    b.Property<string>("Slug")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)")
                        .HasColumnName("slug");

                    b.Property<Guid>("SourceId")
                        .HasColumnType("uuid")
                        .HasColumnName("source_id");

                    b.Property<DateTime?>("SourcePublishedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("source_published_at_utc");

                    b.Property<string>("SourceType")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("source_type");

                    b.Property<DateTime>("SourceUpdatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("source_updated_at_utc");

                    b.Property<string>("Summary")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("summary");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)")
                        .HasColumnName("title");

                    b.Property<string>("Url")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("url");

                    b.HasKey("Id");

                    b.HasIndex("IsPublished")
                        .HasDatabaseName("ix_search_documents_is_published");

                    b.HasIndex("SourceType", "SourceId")
                        .IsUnique()
                        .HasDatabaseName("ux_search_documents_source");

                    b.HasIndex("IsPublished", "SourceType", "Title")
                        .HasDatabaseName("ix_search_documents_published_type_title");

                    b.ToTable("search_documents", (string)null);
                });

            modelBuilder.Entity("HelpDev.Modules.Toolbox.Domain.Categories.ToolCategory", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at_utc");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("description");

                    b.Property<int>("DisplayOrder")
                        .HasColumnType("integer")
                        .HasColumnName("display_order");

                    b.Property<string>("Icon")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("icon");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean")
                        .HasColumnName("is_active");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("name");

                    b.Property<string>("Slug")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("slug");

                    b.Property<DateTime>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at_utc");

                    b.HasKey("Id");

                    b.HasIndex("DisplayOrder")
                        .HasDatabaseName("ix_toolbox_categories_display_order");

                    b.HasIndex("IsActive")
                        .HasDatabaseName("ix_toolbox_categories_is_active");

                    b.HasIndex("Slug")
                        .IsUnique()
                        .HasDatabaseName("ux_toolbox_categories_slug");

                    b.ToTable("toolbox_categories", (string)null);
                });

            modelBuilder.Entity("HelpDev.Modules.Toolbox.Domain.Execution.ToolExecutionRecord", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<int>("DurationMilliseconds")
                        .HasColumnType("integer")
                        .HasColumnName("duration_milliseconds");

                    b.Property<string>("ErrorCode")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("error_code");

                    b.Property<DateTime>("ExecutedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("executed_at_utc");

                    b.Property<string>("InputPreview")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("input_preview");

                    b.Property<string>("OutputPreview")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("output_preview");

                    b.Property<bool>("Succeeded")
                        .HasColumnType("boolean")
                        .HasColumnName("succeeded");

                    b.Property<Guid>("ToolId")
                        .HasColumnType("uuid")
                        .HasColumnName("tool_id");

                    b.Property<string>("ToolType")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("character varying(40)")
                        .HasColumnName("tool_type");

                    b.Property<Guid?>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.HasKey("Id");

                    b.HasIndex("ExecutedAtUtc")
                        .HasDatabaseName("ix_toolbox_execution_records_executed_at_utc");

                    b.HasIndex("Succeeded")
                        .HasDatabaseName("ix_toolbox_execution_records_succeeded");

                    b.HasIndex("ToolId")
                        .HasDatabaseName("ix_toolbox_execution_records_tool_id");

                    b.HasIndex("UserId")
                        .HasDatabaseName("ix_toolbox_execution_records_user_id");

                    b.ToTable("toolbox_execution_records", (string)null);
                });

            modelBuilder.Entity("HelpDev.Modules.Toolbox.Domain.Favorites.ToolFavorite", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at_utc");

                    b.Property<Guid>("ToolId")
                        .HasColumnType("uuid")
                        .HasColumnName("tool_id");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.HasKey("Id");

                    b.HasIndex("ToolId")
                        .HasDatabaseName("ix_toolbox_favorites_tool_id");

                    b.HasIndex("UserId")
                        .HasDatabaseName("ix_toolbox_favorites_user_id");

                    b.HasIndex("UserId", "ToolId")
                        .IsUnique()
                        .HasDatabaseName("ux_toolbox_favorites_user_id_tool_id");

                    b.ToTable("toolbox_favorites", (string)null);
                });

            modelBuilder.Entity("HelpDev.Modules.Toolbox.Domain.Tools.ToolDefinition", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<bool>("AllowHistory")
                        .HasColumnType("boolean")
                        .HasColumnName("allow_history");

                    b.Property<Guid>("CategoryId")
                        .HasColumnType("uuid")
                        .HasColumnName("category_id");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at_utc");

                    b.Property<string>("Description")
                        .HasMaxLength(3000)
                        .HasColumnType("character varying(3000)")
                        .HasColumnName("description");

                    b.Property<int>("DisplayOrder")
                        .HasColumnType("integer")
                        .HasColumnName("display_order");

                    b.Property<string>("ExampleInput")
                        .HasMaxLength(8000)
                        .HasColumnType("character varying(8000)")
                        .HasColumnName("example_input");

                    b.Property<string>("InputSchema")
                        .IsRequired()
                        .HasMaxLength(8000)
                        .HasColumnType("character varying(8000)")
                        .HasColumnName("input_schema");

                    b.Property<bool>("IsEnabled")
                        .HasColumnType("boolean")
                        .HasColumnName("is_enabled");

                    b.Property<bool>("IsPublished")
                        .HasColumnType("boolean")
                        .HasColumnName("is_published");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)")
                        .HasColumnName("name");

                    b.Property<DateTime?>("PublishedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("published_at_utc");

                    b.Property<bool>("RequiresAuthentication")
                        .HasColumnType("boolean")
                        .HasColumnName("requires_authentication");

                    b.Property<string>("Slug")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)")
                        .HasColumnName("slug");

                    b.Property<string>("Summary")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)")
                        .HasColumnName("summary");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("character varying(40)")
                        .HasColumnName("type");

                    b.Property<DateTime>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at_utc");

                    b.HasKey("Id");

                    b.HasIndex("CategoryId")
                        .HasDatabaseName("ix_toolbox_tools_category_id");

                    b.HasIndex("DisplayOrder")
                        .HasDatabaseName("ix_toolbox_tools_display_order");

                    b.HasIndex("IsEnabled")
                        .HasDatabaseName("ix_toolbox_tools_is_enabled");

                    b.HasIndex("IsPublished")
                        .HasDatabaseName("ix_toolbox_tools_is_published");

                    b.HasIndex("Slug")
                        .IsUnique()
                        .HasDatabaseName("ux_toolbox_tools_slug");

                    b.HasIndex("Type")
                        .HasDatabaseName("ix_toolbox_tools_type");

                    b.ToTable("toolbox_tools", (string)null);
                });

            modelBuilder.Entity("HelpDev.Modules.Content.Domain.Entities.Content", b =>
                {
                    b.HasOne("HelpDev.Modules.Identity.Domain.Entities.User", null)
                        .WithMany()
                        .HasForeignKey("AuthorId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("HelpDev.Modules.Learning.Domain.Courses.Lesson", b =>
                {
                    b.HasOne("HelpDev.Modules.Learning.Domain.Courses.Section", null)
                        .WithMany("Lessons")
                        .HasForeignKey("SectionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("HelpDev.Modules.Learning.Domain.Courses.Section", b =>
                {
                    b.HasOne("HelpDev.Modules.Learning.Domain.Courses.Course", null)
                        .WithMany("Sections")
                        .HasForeignKey("CourseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("HelpDev.Modules.Learning.Domain.Enrollments.LessonProgress", b =>
                {
                    b.HasOne("HelpDev.Modules.Learning.Domain.Enrollments.Enrollment", null)
                        .WithMany("LessonProgressEntries")
                        .HasForeignKey("EnrollmentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("HelpDev.Modules.PromptLab.Domain.Favorites.PromptFavorite", b =>
                {
                    b.HasOne("HelpDev.Modules.PromptLab.Domain.Prompts.PromptDefinition", null)
                        .WithMany()
                        .HasForeignKey("PromptDefinitionId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("HelpDev.Modules.PromptLab.Domain.Prompts.PromptDefinition", b =>
                {
                    b.HasOne("HelpDev.Modules.PromptLab.Domain.Categories.PromptCategory", null)
                        .WithMany()
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("HelpDev.Modules.PromptLab.Domain.Prompts.PromptVariable", b =>
                {
                    b.HasOne("HelpDev.Modules.PromptLab.Domain.Prompts.PromptVersion", null)
                        .WithMany("Variables")
                        .HasForeignKey("PromptVersionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("HelpDev.Modules.PromptLab.Domain.Prompts.PromptVersion", b =>
                {
                    b.HasOne("HelpDev.Modules.PromptLab.Domain.Prompts.PromptDefinition", null)
                        .WithMany("Versions")
                        .HasForeignKey("PromptDefinitionId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("HelpDev.Modules.PromptLab.Domain.Rendering.PromptRenderRecord", b =>
                {
                    b.HasOne("HelpDev.Modules.PromptLab.Domain.Prompts.PromptDefinition", null)
                        .WithMany()
                        .HasForeignKey("PromptDefinitionId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("HelpDev.Modules.PromptLab.Domain.Prompts.PromptVersion", null)
                        .WithMany()
                        .HasForeignKey("PromptVersionId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("HelpDev.Modules.Toolbox.Domain.Execution.ToolExecutionRecord", b =>
                {
                    b.HasOne("HelpDev.Modules.Toolbox.Domain.Tools.ToolDefinition", null)
                        .WithMany()
                        .HasForeignKey("ToolId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("HelpDev.Modules.Toolbox.Domain.Favorites.ToolFavorite", b =>
                {
                    b.HasOne("HelpDev.Modules.Toolbox.Domain.Tools.ToolDefinition", null)
                        .WithMany()
                        .HasForeignKey("ToolId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("HelpDev.Modules.Toolbox.Domain.Tools.ToolDefinition", b =>
                {
                    b.HasOne("HelpDev.Modules.Toolbox.Domain.Categories.ToolCategory", null)
                        .WithMany()
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("HelpDev.Modules.Learning.Domain.Courses.Course", b =>
                {
                    b.Navigation("Sections");
                });

            modelBuilder.Entity("HelpDev.Modules.Learning.Domain.Courses.Section", b =>
                {
                    b.Navigation("Lessons");
                });

            modelBuilder.Entity("HelpDev.Modules.Learning.Domain.Enrollments.Enrollment", b =>
                {
                    b.Navigation("LessonProgressEntries");
                });

            modelBuilder.Entity("HelpDev.Modules.PromptLab.Domain.Prompts.PromptDefinition", b =>
                {
                    b.Navigation("Versions");
                });

            modelBuilder.Entity("HelpDev.Modules.PromptLab.Domain.Prompts.PromptVersion", b =>
                {
                    b.Navigation("Variables");
                });
#pragma warning restore 612, 618
        }
    }
}
